version: 2.1

commands:
    composer-install:
        description: "Install dependencies"
        steps:
            - run:
                name: "Execute: composer install"
                command: |
                    if [ ! -f vendor/autoload.php ];then
                        composer global require hirak/prestissimo;
                        composer install --ignore-platform-reqs --no-interaction --no-progress --classmap-authoritative;
                    fi

    restore-composer-cache:
        description: "Restore vendor folder from CircleCI cache"
        steps:
            - restore_cache:
                key: composer-{{ checksum "composer.json" }}-{{ checksum "composer.lock" }}

    store-composer-cache:
        description: "Store vendor folder in CircleCI cache"
        steps:
            - checkout
            - composer-install
            - save_cache:
                key: composer-{{ checksum "composer.json" }}-{{ checksum "composer.lock" }}
                paths:
                  - ./vendor
            - persist_to_workspace:
                root: .
                paths:
                  - vendor

    phpunit:
        description: "Execute PHPunit"
        steps:
            - run:
                name: "Execute: vendor/bin/phpunit"
                command: vendor/bin/phpunit tests

executors:
    composer_cache:
        docker:
            - image: composer
        working_directory: ~/repository

    php:
        docker:
            - image: php:7.3.8-cli-alpine3.10
        working_directory: ~/repository

jobs:
    composer:
        executor: composer_cache
        steps:
            - store-composer-cache

    phpunit:
        executor: php
        steps:
            - checkout
            - restore-composer-cache
            - phpunit

workflows:
    version: 2.1
    Code quality:
        jobs:
            - composer
            - phpunit:
                requires:
                    - composer
